# Generated by Django 4.2.11 on 2024-03-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_day_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='total_cal',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
