# Generated by Django 4.2.11 on 2024-03-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_day_total_cal'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='total_carbs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='total_fats',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='total_protein',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
